version: '3'

networks:
  nw_wapp_sandbox:

services:
  nginx:
    restart: always
    container_name: wapp_sandbox_nginx
    hostname: wapp_sandbox.local
    image: wapp_sandbox_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php_fpm
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    env_file:
      - ./docker/.env
    networks:
      - nw_wapp_sandbox

  php_fpm:
    restart: always
    container_name: wapp_sandbox_php_fpm
    hostname: php_fpm
    image: wapp_sandbox_php_fpm
    build:
      context: ./docker/php-workspace
      dockerfile: Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/php-workspace/logs/log1:/var/log/
      - ./docker/php-workspace/logs/log2:/usr/local/var/log
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    env_file:
      - ./docker/.env
    networks:
      - nw_wapp_sandbox